### ISSUE TITLE
PNG Support

### ISSUE THREAD

**Issue by AzureBerylBlue** [aboood40091/BFRES-Tool#8]
Would it be possible to add PNG support to BFRES Tool?

**Comment by Pysis868** [comment]
I finally got a product to work that was an active tool and read both BFRES formats for Switch U and Switch at https://github.com/KillzXGaming/Switch-Toolbox/.  It has a GUI like this one, maybe a bit lacking in details, but also a batch mode and greater file support too!  Probably thanks to the additional `Syroot.NintenTools.NSW.Bfres.dll` library where most other projects only used,  `Syroot.NintenTools.Bfres.dll`, and this one was just manually/internally implemented.

**Comment by aboood40091** [comment]
This tool is outdated. I also recommend Switch Toolbox that has been linked above. (I personally helped with texture support in it)

As for the original issue, I'm making a general library for Wii U textures that supports importing and exporting both DDS and PNG and is much more accurate than anything out there atm, but I don't know if I'll be updating this specific tool as, like I said, I recommend using Switch Toolbox since it has a better UI, more options and does not involve hacky methods this tool uses.
Tools that will certainly be updated to use the new library are GTX Extractor and BFLIM Extractor.

**Comment by AzureBerylBlue** [comment]
Sorry. It's been over a year, so I forgot that I posted this. I've already switched to using Switch Toolbox.
